services:
  truck-management:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/truckmanagement
      - JWT_SECRET=mysecret
      - NODE_ENV=development
    container_name: truck-management-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    command: >
      sh -c "npx prisma db push && node dist/main"

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: truckmanagement
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
